### ISSUE TITLE
missing templates and obsolete references

### ISSUE THREAD

**Issue by jparicka** [jparicka/twitter-tools#1]
Exception raised while rendering {% include %} for template 'dashboard.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 200, in render
    template = context.template.engine.get_template(template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 169, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
TemplateDoesNotExist: google_analytics.html

**Comment by jparicka** [comment]
fixed
